### ISSUE TITLE
[Map] allow to show trail for specific location source

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/web#117]
E.g. only GNSS.

This needs backend changes, because we currently don't store the source in Timestream.

**Comment by gregersrygg** [comment]
To expand on this, it would also be nice to have a separate trail and color for each location source. It looks like they're all mixed in the same trail causing a very jagged trail:
![IMG_4842](https://github.com/user-attachments/assets/63e52b1e-1370-415f-bf65-8c56373af9b3)

**Comment by coderbyheart** [comment]
I'll close this for now because the sources have been separated.
