### ISSUE TITLE
The first location shown is very zoomed in

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/web#794]
Its not easy to see (without changing zoom) where the device is when first entering the page.

![image](https://github.com/user-attachments/assets/6c8fa2e9-96a2-4829-a3ee-83af1864144d)

**Comment by coderbyheart** [comment]
What do you suggest the first zoom level to be?

**Comment by simensrostad** [comment]
Would be nice to see what city / part of the city you are in. I don't have a reference to zoom level, but googles 14z is nice:

https://www.google.com/maps/@63.4249306,10.4301998,14z?entry=ttu&g_ep=EgoyMDI0MDkyNC4wIKXMDSoASAFQAw%3D%3D
