### ISSUE TITLE
Potential confusion on LED pattern indicator

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/web#796]
During testing some users thought that the displayed auto led pattern was the actual real time operational state/pattern for the device:

![image](https://github.com/user-attachments/assets/c8a45f55-6fa3-43be-a958-f8de346feaa3)

**Comment by coderbyheart** [comment]
Happy to receive suggestions on how to improve the pattern documentation. I believe the text makes it clear that it's not the actual pattern.

**Comment by simensrostad** [comment]
I think the animations is what throws them off. Some even tried to click on them.
