### ISSUE TITLE
Confusion on the button press

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/web#798]
Users expects some indication for when the button is pressed. The message under the "changing LED" section is also a bit vague as users don't know what pressing the button will result in:

![image](https://github.com/user-attachments/assets/f7d3c1c4-f8f3-4d70-9dd8-9110dde27c4a)

They wasn't sure what "them" is referring to.

**Comment by coderbyheart** [comment]
Button presses are shown when the device reports them. If they are not shown the device most likely did not send them.

You can see the reported state in the LwM2M objects pane. Look for the object 14220.

**Comment by coderbyheart** [comment]
I found out why the button presses did not show up. This is now getting fixed: https://github.com/hello-nrfcloud/proto-map/commit/a9b9359091079f773aafc1630a760a3d77b6be45
