### ISSUE TITLE
Use "standard" map color theme as default

### ISSUE THREAD

**Issue by jtguggedal** [hello-nrfcloud/web#804]
I suggest we use a "standard" map layout as default, so that users quickly can see where a device is located in a familiar map layout.

By "standard" I mean a theme similar to Bing, Google maps and the likes, where water is blue and there are in general more colors to easily differentiate between main roads, smaller roads, forest, mountains etc.

It would also be very nice if the map could have more labels on roads, major buildings etc. Currently it seems quite minimalistic.

**Comment by coderbyheart** [comment]
This is intentional but we can add a theme style switcher (like we have for dark/bright style).
